.PHONY: clean All

All:
	@echo "----------Building project:[ CPPString - Debug ]----------"
	@cd "CPPString" && "$(MAKE)" -f  "CPPString.mk"
clean:
	@echo "----------Cleaning project:[ CPPString - Debug ]----------"
	@cd "CPPString" && "$(MAKE)" -f  "CPPString.mk" clean
